application: ze-boutique
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css
  http_headers:
    Vary: Accept-Encoding
  expiration: "7d"

- url: /static/images
  static_dir: static/images
  http_headers:
    Vary: Accept-Encoding
  expiration: "7d"

- url: /.*
  script: main.app
  secure: always


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
